### PR TITLE
Adds winDir scatter plot as per issue #57

### PR DESCRIPTION
**Pull request by W0CHP**
Per issue #57 , this PR adds windDir scatter plots to templates.

### CODE REVIEW

**Comment by seehase** [comment]
Hi @W0CHP 
There is a small bug in the templates for yesterday, week, month and year templates when using windDir
The graph-type is "line" but the config is not defined

You need to add 

```
  var graph_line_config = {
    #include "graph_line_config.inc"
  }
```
to the template, as it is already in the "year-%Y-$m.html.tmpl" for example
see here
https://github.com/seehase/neowx-material/blob/9ef0d2725e8eeb9043fef5efbcb0844879a49794/src/year.html.tmpl#L319

**Comment by W0CHP** [comment]
@seehase thanks! I've fixed the issue :)

**Comment by seehase** [comment]
I can see " All-Time Records" in your stat... I like to add this too... How did you do this?
alos like the icons in your headlines. 
can you send me the code ... or create a PR for my fork ;-)

**Comment by W0CHP** [comment]
> I can see " All-Time Records" in your stat... I like to add this too... How did you do this? alos like the icons in your headlines. can you send me the code ... or create a PR for my fork ;-)

@seehase I see you already have the F-A icons working.  👍  Can't do a PR (won't let me since I already have the original repo  forked), but I'll post the all-time records template snippet in your PR #54 shortly ;-)

**Pull request closed without merging**
