### PR TITLE
Fix python 3.8 warnings related to identity checks

### PR DESCRIPTION
**Pull request by chrismiceli**
This addresses warning when generating the html files:
image

### CODE REVIEW

**Comment by neoground** [comment]
Thank you! 👍

**Comment by ThomDietrich** [comment]
Came here to report this issue. Thanks @chrismiceli !

@neoground no rush but when is this available as a release?

**Comment by chrismiceli** [comment]
> Came here to report this issue. Thanks @chrismiceli !

Glad to be of help.

**Comment by ThomDietrich** [comment]
Hello @neoground could you please upload a new release including this change!? Much appreciated.

**Pull request merged**
